version: '2.1'

services:
  user-profile-bridge:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/idam/user-profile-bridge
    ports:
      - $SERVER_PORT:$SERVER_PORT
