version: '2.1'

services:
  user-profile-bridge:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/idam/user-profile-bridge
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres?ssl=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example
