java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/idam/user-profile-bridge:latest'
  ingressHost: idam-user-profile-bridge-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: idam
  environment:
    IDAM_API_URL: http://idam-api.service.core-compute-{{ .Values.global.environment }}.internal
    RD_USERPROFILE_API_URL: http://rd-user-profile-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    RPE_CASEWORKER_API_URL: http://rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/jwks
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_IDAMUSERPROFILEBRIDGE_TOKENURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/token
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_RDUSERPROFILEAPI_TOKENURI: http://idam-web-public.service.core-compute-{{ .Values.global.environment }}.internal/o/token
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secrets:
        - name: AppInsightsConnectionString
          alias: app-insights-connection-string
        - name: idam-user-profile-bridge-client-secret
          alias: spring.security.oauth2.client.registration.idam-user-profile-bridge.client-secret
        - name: idam-user-profile-bridge-client-secret
          alias: spring.security.oauth2.client.registration.rd-userprofile-api.client-secret
        - name: idam-user-profile-bridge-rd-system-username
          alias: rd.userprofile.client.registration.service-account-user
        - name: idam-user-profile-bridge-rd-system-password
          alias: rd.userprofile.client.registration.service-account-password
